## Import libraires

In [ ]:
import torch
import transformers
from huggingface_hub import notebook_login
import pandas as pd

transformers.__version__

'4.57.3'

In [ ]:
notebook_login()

VBox(children=(HTML(value='<center> <img\nsrc=https://huggingface.co/front/assets/huggingface_logo-noborder.sv…

In [ ]:
# !pip install datasets

----------------------------------------------------------------------
----------------------------------------------------------------------
----------------------------------------------------------------------

In [ ]:
from transformers import AutoModelForCausalLM
from transformers import AutoTokenizer

## Generating Text

In [ ]:
from transformers import AutoTokenizer

In [ ]:
tokenizer = AutoTokenizer.from_pretrained("gpt2")

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

tokenizer_config.json:   0%|          | 0.00/26.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/665 [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/1.04M [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/456k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.36M [00:00<?, ?B/s]

In [ ]:
sentence = "unsure"
input_ids = tokenizer(sentence, return_tensors="pt").input_ids
input_ids

tensor([[13271,   495]])

In [ ]:
tokenizer.decode(input_ids[0])

'unsure'

In [ ]:
sentence = "unbelivable"
input_ids = tokenizer(sentence, return_tensors="pt").input_ids
input_ids

tensor([[  403,  6667, 21911]])

In [ ]:
tokenizer.decode(input_ids[0])

'unbelivable'

In [ ]:
sentence = "homoscedasticity"
input_ids = tokenizer(sentence, return_tensors="pt").input_ids
input_ids

tensor([[26452,   418,   771,  3477,   414]])

`words -> Tokens -> Unique ID -> Vector Embed`

In [ ]:
tokenizer.decode(torch.tensor([26452, 418, 771, 3477, 414]))

'homoscedasticity'

In [ ]:
sentence = "pneumonoultramicroscopicsilicovolcanoconiosis"
input_ids = tokenizer(sentence, return_tensors="pt").input_ids
input_ids

tensor([[   79, 25668,   261, 25955,   859,  2500,  1416,   404,   873, 41896,
           709,   349,  5171, 36221, 42960]])

In [ ]:
for token_id in input_ids[0]:
    print(tokenizer.decode(token_id))

p
neum
on
oult
ram
icro
sc
op
ics
ilic
ov
ol
can
ocon
iosis

In [ ]:
tokenizer.decode(torch.tensor([ 79, 25668,   261, 25955,   859,  2500,  1416,   404,   873, 41896,
           709,   349,  5171, 36221, 42960]))

'pneumonoultramicroscopicsilicovolcanoconiosis'

In [ ]:
sentence = "antidisestablishmentarianism"
input_ids = tokenizer(sentence, return_tensors="pt").input_ids
input_ids

tensor([[  415, 29207, 44390,  3699,  1042]])

In [ ]:
tokenizer.decode(torch.tensor([415, 29207, 44390,  3699,  1042]))

'antidisestablishmentarianism'

In [ ]:
sentence = "floccinaucinihilipilification"
input_ids = tokenizer(sentence, return_tensors="pt").input_ids
input_ids

tensor([[ 2704, 13966,   259, 14272,   259, 20898,   541,   346,  2649]])

In [ ]:
tokenizer.decode(torch.tensor([2704, 13966,   259, 14272,   259, 20898,   541,   346,  2649]))

'floccinaucinihilipilification'

In [ ]:
tokenizer.decode([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

'!"#$%&\'()*+'

In [ ]:
tokenizer.decode([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25])

',-./0123456789:'

In [ ]:
tokenizer.decode([26, 27, 28, 29, 30, 32, 33])

';<=>?AB'

In [ ]:
tokenizer.decode([100, 101, 1000, 1001])

'��ale Se'

In [ ]:
tokenizer.decode([60, 61, 70, 71])

']^gh'

In [ ]:
tokenizer.decode([202])

'\x0e'

In [ ]:
sentence = "I skip across the"
input_ids = tokenizer(sentence, return_tensors="pt").input_ids
input_ids

tensor([[   40, 14267,  1973,   262]])

In [ ]:
from transformers import AutoModelForCausalLM

In [ ]:
gpt2 = AutoModelForCausalLM.from_pretrained("gpt2")

model.safetensors:   0%|          | 0.00/548M [00:00<?, ?B/s]

generation_config.json:   0%|          | 0.00/124 [00:00<?, ?B/s]

In [ ]:
input_ids

tensor([[   40, 14267,  1973,   262]])

In [ ]:
outputs = gpt2(input_ids)

In [ ]:
outputs.logits.shape

torch.Size([1, 4, 50257])

In [ ]:
outputs.logits

tensor([[[-39.3084, -39.0100, -41.8374,  ..., -46.9337, -44.9074, -39.5149],
         [-78.0579, -78.4766, -82.9907,  ..., -87.3914, -86.9835, -79.6007],
         [-73.0664, -74.0119, -78.5555,  ..., -81.0934, -82.5249, -75.8570],
         [-87.5486, -86.0567, -88.3320,  ..., -88.2509, -90.5480, -86.1209]]],
       grad_fn=<UnsafeViewBackward0>)

In [ ]:
final_logits = gpt2(input_ids).logits[0, -1]

In [ ]:
final_logits

tensor([-87.5486, -86.0567, -88.3320,  ..., -88.2509, -90.5480, -86.1209],
       grad_fn=<SelectBackward0>)

In [ ]:
final_logits.argmax() # Token ID <--> Index location Logits

tensor(1627)

In [ ]:
tokenizer.decode(final_logits.argmax())

' line'

In [ ]:
top10_logits = torch.topk(final_logits, 20)

In [ ]:
for index in top10_logits.indices:
    print(tokenizer.decode(index))

 line
 street
 river
 room
 pond
 bridge
 border
 country
 road
 board
 floor
 table
 world
 entire
 ocean
 whole
 streets
 field
 top
 lines

In [ ]:
sentence = "I like machine learning to be able to predict the future."
output = gpt2(tokenizer(sentence, return_tensors="pt").input_ids)
tokenizer.decode(output.logits[0, -1].argmax())

NameError: name 'gpt2' is not defined

In [ ]:
sentence = "I like shopping for things that are really good for you. I like to buy things that are"
output = gpt2(tokenizer(sentence, return_tensors="pt").input_ids)
tokenizer.decode(output.logits[0, -1].argmax())

' really'

In [ ]:
sentence = "I learn in university about machine learning and how to use it to improve your learning"
output = gpt2(tokenizer(sentence, return_tensors="pt").input_ids)
tokenizer.decode(output.logits[0, -1].argmax())

'.'

In [ ]:
sentence = "I like shopping with people who are like my"
output = gpt2(tokenizer(sentence, return_tensors="pt").input_ids)
final_logits = output.logits[0, -1]
tokenizer.decode(output.logits[0, -1].argmax())

top10_logits = torch.topk(final_logits, 10)
for index in top10_logits.indices:
    print(tokenizer.decode(index))

 family
 friends
 mom
 parents
 dad
 wife
 brother
 friend
 sister
 grandparents

In [ ]:
sentence = "I like shopping with people who are like my"
output = gpt2(tokenizer(sentence, return_tensors="pt").input_ids)
final_logits = output.logits[0, -1]
tokenizer.decode(output.logits[0, -1].argmax())

top10_logits = torch.topk(final_logits, 10)
for index in top10_logits.indices:
    print(tokenizer.decode(index))

 family
 friends
 mom
 parents
 dad
 wife
 brother
 friend
 sister
 grandparents

In [ ]:
import torch
import torch.nn.functional as F

# ---------------------------
# 1. Greedy Decoding (Argmax)
# ---------------------------
def greedy_decode(logits):
    """Return token index with maximum probability."""
    return torch.argmax(logits, dim=-1)


# ---------------------------
# 2. Top-k Sampling
# ---------------------------
def top_k_sampling(logits, k=50):
    """
    Keep only top-k logits, normalize them into probabilities,
    then sample one token from the filtered distribution.
    """
    values, indices = torch.topk(logits, k)
    probs = F.softmax(values, dim=-1)
    sampled = torch.multinomial(probs, 1)
    return indices[sampled]


# ---------------------------
# 3. Top-p (Nucleus) Sampling
# ---------------------------
def top_p_sampling(logits, p=0.9):
    """
    Sort tokens by probability, keep smallest number whose cumulative
    probability exceeds 'p', then sample one token.
    """
    sorted_logits, sorted_indices = torch.sort(logits, descending=True)
    sorted_probs = F.softmax(sorted_logits, dim=-1)
    cumulative_probs = sorted_probs.cumsum(dim=-1)

    # Mask tokens outside nucleus
    mask = cumulative_probs > p
    sorted_logits[mask] = float('-inf')

    # Sample from filtered logits
    filtered_probs = F.softmax(sorted_logits, dim=-1)
    sampled = torch.multinomial(filtered_probs, 1)

    # Return token index in original vocabulary
    return sorted_indices[sampled]


# ---------------------------
# 4. Temperature Sampling
# ---------------------------
def temperature_sampling(logits, temperature=1.0):
    """
    Scale logits by temperature before sampling.
    Lower temperature → sharper distribution.
    """
    scaled = logits / temperature
    probs = F.softmax(scaled, dim=-1)
    return torch.multinomial(probs, 1)


# ---------------------------
# 5. Random Sampling from Full Distribution
# ---------------------------
def random_sampling(logits):
    """
    Sample directly from softmax distribution without filtering.
    """
    probs = F.softmax(logits, dim=-1)
    return torch.multinomial(probs, 1)


# ---------------------------
# 6. Utility: Get Top-k Tokens for Display
# ---------------------------
def top_k_tokens(logits, tokenizer, k=10):
    values, indices = torch.topk(logits, k)
    return [(tokenizer.decode([idx]), float(values[i])) for i, idx in enumerate(indices)]


sentence = "Today I decided to go to the local mall and"
inputs = tokenizer(sentence, return_tensors="pt")
output = gpt2(**inputs)
logits = output.logits[0, -1]

print("Greedy:", tokenizer.decode([greedy_decode(logits)]))
print("Top-k:", tokenizer.decode(top_k_sampling(logits, k=10)))
print("Top-p:", tokenizer.decode(top_p_sampling(logits, p=0.9)))
print("Temp:", tokenizer.decode(temperature_sampling(logits, temperature=0.7)))
print("Random:", tokenizer.decode(random_sampling(logits)))
print(f"==============\n")

top10 = torch.topk(logits.softmax(dim=0), 10)
for value, index in zip(top10.values, top10.indices):
    print(f"{tokenizer.decode(index)} -- {value:.1%}")

Greedy:  buy
Top-k:  I
Top-p:  buy
Temp:  was
Random:  bought
==============

 buy -- 23.4%
 bought -- 6.2%
 see -- 4.3%
 get -- 3.9%
 try -- 3.1%
 pick -- 3.0%
 purchase -- 2.7%
 check -- 2.6%
 I -- 2.6%
 find -- 2.5%

In [ ]:
final_logits.softmax(dim=0)

tensor([2.7841e-06, 1.6066e-05, 5.8392e-08,  ..., 4.2602e-06, 1.3941e-08,
        1.0811e-06], grad_fn=<SoftmaxBackward0>)

In [ ]:
top10 = torch.topk(final_logits.softmax(dim=0), 10)
top10

torch.return_types.topk(
values=tensor([0.1169, 0.0993, 0.0722, 0.0557, 0.0395, 0.0320, 0.0263, 0.0210, 0.0208,
        0.0193], grad_fn=<TopkBackward0>),
indices=tensor([ 1641,  2460,  1995,  3397,  9955,  3656,  3956,  1545,  6621, 28571]))

In [ ]:
for value, index in zip(top10.values, top10.indices):
    print(f"{tokenizer.decode(index)} -- {value.item():.1%}")

 family -- 11.7%
 friends -- 9.9%
 mom -- 7.2%
 parents -- 5.6%
 dad -- 3.9%
 wife -- 3.2%
 brother -- 2.6%
 friend -- 2.1%
 sister -- 2.1%
 grandparents -- 1.9%

In [ ]:
output_ids = gpt2.generate(input_ids, max_new_tokens=20)

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
The attention mask is not set and cannot be inferred from input because pad token is same as eos token. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.

In [ ]:
decoded_text = tokenizer.decode(output_ids[0])
decoded_text

'I skip across the line to the next section.\n\nThe first thing to note is that the first line is a'

In [ ]:
output_ids = gpt2.generate(input_ids, max_new_tokens=200)

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

In [ ]:
print(tokenizer.decode(output_ids[0]))

I skip across the line to the next section.

The first thing to note is that the first line is a list of all the items in the list. This is a list of all the items in the list. The second line is a list of all the items in the list. This is a list of all the items in the list. The third line is a list of all the items in the list. This is a list of all the items in the list. The fourth line is a list of all the items in the list. This is a list of all the items in the list. The fifth line is a list of all the items in the list. This is a list of all the items in the list. The sixth line is a list of all the items in the list. This is a list of all the items in the list. The seventh line is a list of all the items in the list. This is a list of all the items in the list. The eighth line

In [ ]:
output_ids = gpt2.generate(input_ids, max_new_tokens=200, repetition_penalty=1.5, do_sample=True, top_k=5, top_p=0.94)

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

In [ ]:
output_ids = gpt2.generate(input_ids, max_new_tokens=20, repetition_penalty=1.5, do_sample=True, temperature=0.5)

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

In [ ]:
decoded_text = tokenizer.decode(output_ids[0])

In [ ]:
print(decoded_text)

I skip across the line and go to a different part of town.

The next morning, I was in my

In [ ]:
# Use a pipeline as a high-level helper
from transformers import pipeline

pipe = pipeline("text-generation", model="openai-community/gpt2")

config.json:   0%|          | 0.00/665 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/548M [00:00<?, ?B/s]

generation_config.json:   0%|          | 0.00/124 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/26.0 [00:00<?, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

Device set to use cuda:0

In [ ]:
pipe("I went to the store and bought a")

Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

[{'generated_text': "I went to the store and bought a small backpack I bought for my mother. I went over the product and then went through the product and found out that it was a little different. I bought it for my sister and her sister also. She was a very young girl and I was very upset about that. But I didn't go over to the store and buy the product because she was so young and she didn't want to buy it.\n\nWe had a different family and we were told that they had to take care of the kids. I was just so upset. I'm so glad we found this stuff and then went to the store and bought it. It's amazing. It's very cool.\n\nWhat do you think of the new Hennepin County Sheriff's department?\n\nI'm in love with this department and I'm excited to be doing what I love doing. I'm looking forward to it.\n\nWhat did you think of the new sheriff's department?\n\nHe's a great guy. He's a gentleman. I think he's very smart and he's a good sheriff. It's going to be great for us. We've got a lot of new people coming in. I think the sheriff's department is going to have a lot of potential.\n"}]

In [ ]:
pipe("What is machine learning?")

Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

[{'generated_text': 'What is machine learning?\n\nMachine learning is a process of taking data from a computer and combining it with other data. It is a process of finding and processing information in a way that is more similar to human vision. It is a process of creating a representation in a way that is more real than human vision. The process is called machine learning.\n\nHow does machine learning compare to human vision?\n\nMachine learning compares to human vision when it comes to looking at a visual world. We have the ability to determine the position of objects using the visual system. We can determine where objects are in the world. We can determine what they look like in the world.\n\nWhat are the challenges and challenges of machine learning?\n\nMachine learning is a process of processing information through the use of a computer. In our case, we are trying to find a way to make a better representation of the image in a computer. We are trying to find a way to make a better representation of the object in a computer.\n\nWhat are some of the challenges with machine learning?\n\nIn our case, as we move from image processing to computation, we have to be able to do some of the new techniques that we use to train machine learning. We have to be able to find'}]

In [ ]:
pipe(sentences)

[{'label': 'positive', 'score': 0.9434744715690613},
 {'label': 'negative', 'score': 0.9659876823425293}]

----------------------------------------------------------------------
----------------------------------------------------------------------
----------------------------------------------------------------------

## Sentiment Analysis

In [ ]:
from datasets import load_dataset

dataset = load_dataset("stanfordnlp/imdb")

README.md: 0.00B [00:00, ?B/s]

plain_text/train-00000-of-00001.parquet:   0%|          | 0.00/21.0M [00:00<?, ?B/s]

plain_text/test-00000-of-00001.parquet:   0%|          | 0.00/20.5M [00:00<?, ?B/s]

plain_text/unsupervised-00000-of-00001.p(…):   0%|          | 0.00/42.0M [00:00<?, ?B/s]

Generating train split:   0%|          | 0/25000 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/25000 [00:00<?, ? examples/s]

Generating unsupervised split:   0%|          | 0/50000 [00:00<?, ? examples/s]

In [ ]:
dataset

DatasetDict({
    train: Dataset({
        features: ['text', 'label'],
        num_rows: 25000
    })
    test: Dataset({
        features: ['text', 'label'],
        num_rows: 25000
    })
    unsupervised: Dataset({
        features: ['text', 'label'],
        num_rows: 50000
    })
})

In [ ]:
type(dataset)

datasets.dataset_dict.DatasetDict

In [ ]:
dataset["train"]

Dataset({
    features: ['text', 'label'],
    num_rows: 25000
})

In [ ]:
help(dataset["train"])

Help on Dataset in module datasets.arrow_dataset object:

class Dataset(DatasetInfoMixin, datasets.search.IndexableMixin, TensorflowDatasetMixin)
 |  Dataset(arrow_table: datasets.table.Table, info: Optional[datasets.info.DatasetInfo] = None, split: Optional[datasets.splits.NamedSplit] = None, indices_table: Optional[datasets.table.Table] = None, fingerprint: Optional[str] = None)
 |
 |  A Dataset backed by an Arrow table.
 |
 |  Method resolution order:
 |      Dataset
 |      DatasetInfoMixin
 |      datasets.search.IndexableMixin
 |      TensorflowDatasetMixin
 |      builtins.object
 |
 |  Methods defined here:
 |
 |  __del__(self)
 |
 |  __enter__(self)
 |
 |  __exit__(self, exc_type, exc_val, exc_tb)
 |
 |  __getitem__(self, key)
 |      Can be used to index columns (by string names) or rows (by integer index or iterable of indices or bools).
 |
 |  __getitems__(self, keys: list) -> list
 |      Can be used to get a batch using a list of integers indices.
 |
 |  __init__(self, arrow_table: datasets.table.Table, info: Optional[datasets.info.DatasetInfo] = None, split: Optional[datasets.splits.NamedSplit] = None, indices_table: Optional[datasets.table.Table] = None, fingerprint: Optional[str] = None)
 |      Initialize self.  See help(type(self)) for accurate signature.
 |
 |  __iter__(self)
 |      Iterate through the examples.
 |
 |      If a formatting is set with [`Dataset.set_format`] rows will be returned with the
 |      selected format.
 |
 |  __len__(self)
 |      Number of rows in the dataset.
 |
 |      Example:
 |
 |      ```py
 |      >>> from datasets import load_dataset
 |      >>> ds = load_dataset("cornell-movie-review-data/rotten_tomatoes", split="validation")
 |      >>> ds.__len__
 |      <bound method Dataset.__len__ of Dataset({
 |          features: ['text', 'label'],
 |          num_rows: 1066
 |      })>
 |      ```
 |
 |  __repr__(self)
 |      Return repr(self).
 |
 |  __setstate__(self, state)
 |
 |  add_column(self, name: str, column: Union[list, numpy.ndarray], new_fingerprint: str, feature: Union[dict, list, tuple, datasets.features.features.Value, datasets.features.features.ClassLabel, datasets.features.translation.Translation, datasets.features.translation.TranslationVariableLanguages, datasets.features.features.LargeList, datasets.features.features.List, datasets.features.features.Array2D, datasets.features.features.Array3D, datasets.features.features.Array4D, datasets.features.features.Array5D, datasets.features.audio.Audio, datasets.features.image.Image, datasets.features.video.Video, datasets.features.pdf.Pdf, NoneType] = None)
 |      Add column to Dataset.
 |
 |      <Added version="1.7"/>
 |
 |      Args:
 |          name (`str`):
 |              Column name.
 |          column (`list` or `np.array`):
 |              Column data to be added.
 |          feature (`FeatureType` or `None`, defaults to `None`):
 |              Column datatype.
 |
 |      Returns:
 |          [`Dataset`]
 |
 |      Example:
 |
 |      ```py
 |      >>> from datasets import load_dataset
 |      >>> ds = load_dataset("cornell-movie-review-data/rotten_tomatoes", split="validation")
 |      >>> more_text = ds["text"]
 |      >>> ds.add_column(name="text_2", column=more_text)
 |      Dataset({
 |          features: ['text', 'label', 'text_2'],
 |          num_rows: 1066
 |      })
 |      ```
 |
 |  add_elasticsearch_index(self, column: str, index_name: Optional[str] = None, host: Optional[str] = None, port: Optional[int] = None, es_client: Optional[ForwardRef('elasticsearch.Elasticsearch')] = None, es_index_name: Optional[str] = None, es_index_config: Optional[dict] = None)
 |      Add a text index using ElasticSearch for fast retrieval. This is done in-place.
 |
 |      Args:
 |          column (`str`):
 |              The column of the documents to add to the index.
 |          index_name (`str`, *optional*):
 |              The `index_name`/identifier of the index.
 |              This is the index name that is used to call [`~Dataset.get_nearest_examples`] or [`~Dataset.search`].
 |              By default it corresponds to `column`.
 |          host (`str`, *optional*, defaults to `localhost`):
 |              Host of where ElasticSearch is running.
 |          port (`str`, *optional*, defaults to `9200`):
 |              Port of where ElasticSearch is running.
 |          es_client (`elasticsearch.Elasticsearch`, *optional*):
 |              The elasticsearch client used to create the index if host and port are `None`.
 |          es_index_name (`str`, *optional*):
 |              The elasticsearch index name used to create the index.
 |          es_index_config (`dict`, *optional*):
 |              The configuration of the elasticsearch index.
 |              Default config is:
 |                  ```
 |                  {
 |                      "settings": {
 |                          "number_of_shards": 1,
 |                          "analysis": {"analyzer": {"stop_standard": {"type": "standard", " stopwords": "_english_"}}},
 |                      },
 |                      "mappings": {
 |                          "properties": {
 |                              "text": {
 |                                  "type": "text",
 |                                  "analyzer": "standard",
 |                                  "similarity": "BM25"
 |                              },
 |                          }
 |                      },
 |                  }
 |                  ```
 |      Example:
 |
 |      ```python
 |      >>> es_client = elasticsearch.Elasticsearch()
 |      >>> ds = datasets.load_dataset('crime_and_punish', split='train')
 |      >>> ds.add_elasticsearch_index(column='line', es_client=es_client, es_index_name="my_es_index")
 |      >>> scores, retrieved_examples = ds.get_nearest_examples('line', 'my new query', k=10)
 |      ```
 |
 |  add_faiss_index(self, column: str, index_name: Optional[str] = None, device: Optional[int] = None, string_factory: Optional[str] = None, metric_type: Optional[int] = None, custom_index: Optional[ForwardRef('faiss.Index')] = None, batch_size: int = 1000, train_size: Optional[int] = None, faiss_verbose: bool = False, dtype=<class 'numpy.float32'>)
 |      Add a dense index using Faiss for fast retrieval.
 |      By default the index is done over the vectors of the specified column.
 |      You can specify `device` if you want to run it on GPU (`device` must be the GPU index).
 |      You can find more information about Faiss here:
 |
 |      - For [string factory](https://github.com/facebookresearch/faiss/wiki/The-index-factory)
 |
 |      Args:
 |          column (`str`):
 |              The column of the vectors to add to the index.
 |          index_name (`str`, *optional*):
 |              The `index_name`/identifier of the index.
 |              This is the `index_name` that is used to call [`~datasets.Dataset.get_nearest_examples`] or [`~datasets.Dataset.search`].
 |              By default it corresponds to `column`.
 |          device (`Union[int, List[int]]`, *optional*):
 |              If positive integer, this is the index of the GPU to use. If negative integer, use all GPUs.
 |              If a list of positive integers is passed in, run only on those GPUs. By default it uses the CPU.
 |          string_factory (`str`, *optional*):
 |              This is passed to the index factory of Faiss to create the index.
 |              Default index class is `IndexFlat`.
 |          metric_type (`int`, *optional*):
 |              Type of metric. Ex: `faiss.METRIC_INNER_PRODUCT` or `faiss.METRIC_L2`.
 |          custom_index (`faiss.Index`, *optional*):
 |              Custom Faiss index that you already have instantiated and configured for your needs.
 |          batch_size (`int`):
 |              Size of the batch to use while adding vectors to the `FaissIndex`. Default value is `1000`.
 |              <Added version="2.4.0"/>
 |          train_size (`int`, *optional*):
 |              If the index needs a training step, specifies how many vectors will be used to train the index.
 |          faiss_verbose (`bool`, defaults to `False`):
 |              Enable the verbosity of the Faiss index.
 |          dtype (`data-type`):
 |              The dtype of the numpy arrays that are indexed.
 |              Default is `np.float32`.
 |
 |      Example:
 |
 |      ```python
 |      >>> ds = datasets.load_dataset('crime_and_punish', split='train')
 |      >>> ds_with_embeddings = ds.map(lambda example: {'embeddings': embed(example['line']}))
 |      >>> ds_with_embeddings.add_faiss_index(column='embeddings')
 |      >>> # query
 |      >>> scores, retrieved_examples = ds_with_embeddings.get_nearest_examples('embeddings', embed('my new query'), k=10)
 |      >>> # save index
 |      >>> ds_with_embeddings.save_faiss_index('embeddings', 'my_index.faiss')
 |
 |      >>> ds = datasets.load_dataset('crime_and_punish', split='train')
 |      >>> # load index
 |      >>> ds.load_faiss_index('embeddings', 'my_index.faiss')
 |      >>> # query
 |      >>> scores, retrieved_examples = ds.get_nearest_examples('embeddings', embed('my new query'), k=10)
 |      ```
 |
 |  add_faiss_index_from_external_arrays(self, external_arrays: <built-in function array>, index_name: str, device: Optional[int] = None, string_factory: Optional[str] = None, metric_type: Optional[int] = None, custom_index: Optional[ForwardRef('faiss.Index')] = None, batch_size: int = 1000, train_size: Optional[int] = None, faiss_verbose: bool = False, dtype=<class 'numpy.float32'>)
 |      Add a dense index using Faiss for fast retrieval.
 |      The index is created using the vectors of `external_arrays`.
 |      You can specify `device` if you want to run it on GPU (`device` must be the GPU index).
 |      You can find more information about Faiss here:
 |
 |      - For [string factory](https://github.com/facebookresearch/faiss/wiki/The-index-factory)
 |
 |      Args:
 |          external_arrays (`np.array`):
 |              If you want to use arrays from outside the lib for the index, you can set `external_arrays`.
 |              It will use `external_arrays` to create the Faiss index instead of the arrays in the given `column`.
 |          index_name (`str`):
 |              The `index_name`/identifier of the index.
 |              This is the `index_name` that is used to call [`~datasets.Dataset.get_nearest_examples`] or [`~datasets.Dataset.search`].
 |          device (Optional `Union[int, List[int]]`, *optional*):
 |              If positive integer, this is the index of the GPU to use. If negative integer, use all GPUs.
 |              If a list of positive integers is passed in, run only on those GPUs. By default it uses the CPU.
 |          string_factory (`str`, *optional*):
 |              This is passed to the index factory of Faiss to create the index.
 |              Default index class is `IndexFlat`.
 |          metric_type (`int`, *optional*):
 |              Type of metric. Ex: `faiss.faiss.METRIC_INNER_PRODUCT` or `faiss.METRIC_L2`.
 |          custom_index (`faiss.Index`, *optional*):
 |              Custom Faiss index that you already have instantiated and configured for your needs.
 |          batch_size (`int`, *optional*):
 |              Size of the batch to use while adding vectors to the FaissIndex. Default value is 1000.
 |              <Added version="2.4.0"/>
 |          train_size (`int`, *optional*):
 |              If the index needs a training step, specifies how many vectors will be used to train the index.
 |          faiss_verbose (`bool`, defaults to False):
 |              Enable the verbosity of the Faiss index.
 |          dtype (`numpy.dtype`):
 |              The dtype of the numpy arrays that are indexed. Default is np.float32.
 |
 |  add_item(self, item: dict, new_fingerprint: str)
 |      Add item to Dataset.
 |
 |      <Added version="1.7"/>
 |
 |      Args:
 |          item (`dict`):
 |              Item data to be added.
 |
 |      Returns:
 |          [`Dataset`]
 |
 |      Example:
 |
 |      ```py
 |      >>> from datasets import load_dataset
 |      >>> ds = load_dataset("cornell-movie-review-data/rotten_tomatoes", split="validation")
 |      >>> new_review = {'label': 0, 'text': 'this movie is the absolute worst thing I have ever seen'}
 |      >>> ds = ds.add_item(new_review)
 |      >>> ds[-1]
 |      {'label': 0, 'text': 'this movie is the absolute worst thing I have ever seen'}
 |      ```
 |
 |  align_labels_with_mapping(self, label2id: dict, label_column: str) -> 'Dataset'
 |      Align the dataset's label ID and label name mapping to match an input `label2id` mapping.
 |      This is useful when you want to ensure that a model's predicted labels are aligned with the dataset.
 |      The alignment in done using the lowercase label names.
 |
 |      Args:
 |          label2id (`dict`):
 |              The label name to ID mapping to align the dataset with.
 |          label_column (`str`):
 |              The column name of labels to align on.
 |
 |      Example:
 |
 |      ```python
 |      >>> # dataset with mapping {'entailment': 0, 'neutral': 1, 'contradiction': 2}
 |      >>> ds = load_dataset("nyu-mll/glue", "mnli", split="train")
 |      >>> # mapping to align with
 |      >>> label2id = {'CONTRADICTION': 0, 'NEUTRAL': 1, 'ENTAILMENT': 2}
 |      >>> ds_aligned = ds.align_labels_with_mapping(label2id, "label")
 |      ```
 |
 |  batch(self, batch_size: int, drop_last_batch: bool = False, num_proc: Optional[int] = None, new_fingerprint: Optional[str] = None) -> 'Dataset'
 |      Group samples from the dataset into batches.
 |
 |      Args:
 |          batch_size (`int`):
 |              The number of samples in each batch.
 |          drop_last_batch (`bool`, defaults to `False`):
 |              Whether to drop the last incomplete batch.
 |          num_proc (`int`, *optional*, defaults to `None`):
 |              Max number of processes when generating cache. Already cached shards are loaded sequentially.
 |          new_fingerprint (`str`, *optional*, defaults to `None`):
 |              The new fingerprint of the dataset after transform.
 |              If `None`, the new fingerprint is computed using a hash of the previous fingerprint, and the transform arguments.
 |
 |      Returns:
 |          [`Dataset`]: A new Dataset where each item is a batch of multiple samples from the original dataset.
 |
 |      Example:
 |
 |      ```py
 |      >>> from datasets import load_dataset
 |      >>> ds = load_dataset("cornell-movie-review-data/rotten_tomatoes", split="train")
 |      >>> batched_ds = ds.batch(batch_size=4)
 |      >>> batched_ds[0]
 |      {'text': ['compassionately explores the seemingly irreconcilable situation...', ...],  # 4 items
 |      'label': [1, 1, 1, 1]}
 |      ```
 |
 |  cast(self, features: datasets.features.features.Features, batch_size: Optional[int] = 1000, keep_in_memory: bool = False, load_from_cache_file: Optional[bool] = None, cache_file_name: Optional[str] = None, writer_batch_size: Optional[int] = 1000, num_proc: Optional[int] = None) -> 'Dataset'
 |      Cast the dataset to a new set of features.
 |
 |      Args:
 |          features ([`Features`]):
 |              New features to cast the dataset to.
 |              The name of the fields in the features must match the current column names.
 |              The type of the data must also be convertible from one type to the other.
 |              For non-trivial conversion, e.g. `str` <-> `ClassLabel` you should use [`~datasets.Dataset.map`] to update the Dataset.
 |          batch_size (`int`, defaults to `1000`):
 |              Number of examples per batch provided to cast.
 |              If `batch_size <= 0` or `batch_size == None` then provide the full dataset as a single batch to cast.
 |          keep_in_memory (`bool`, defaults to `False`):
 |              Whether to copy the data in-memory.
 |          load_from_cache_file (`bool`, defaults to `True` if caching is enabled):
 |              If a cache file storing the current computation from `function`
 |              can be identified, use it instead of recomputing.
 |          cache_file_name (`str`, *optional*, defaults to `None`):
 |              Provide the name of a path for the cache file. It is used to store the
 |              results of the computation instead of the automatically generated cache file name.
 |          writer_batch_size (`int`, defaults to `1000`):
 |              Number of rows per write operation for the cache file writer.
 |              This value is a good trade-off between memory usage during the processing, and processing speed.
 |              Higher value makes the processing do fewer lookups, lower value consume less temporary memory while running [`~datasets.Dataset.map`].
 |          num_proc (`int`, *optional*, defaults to `None`):
 |              Number of processes for multiprocessing. By default it doesn't
 |              use multiprocessing.
 |
 |      Returns:
 |          [`Dataset`]: A copy of the dataset with casted features.
 |
 |      Example:
 |
 |      ```py
 |      >>> from datasets import load_dataset, ClassLabel, Value
 |      >>> ds = load_dataset("cornell-movie-review-data/rotten_tomatoes", split="validation")
 |      >>> ds.features
 |      {'label': ClassLabel(names=['neg', 'pos']),
 |       'text': Value('string')}
 |      >>> new_features = ds.features.copy()
 |      >>> new_features['label'] = ClassLabel(names=['bad', 'good'])
 |      >>> new_features['text'] = Value('large_string')
 |      >>> ds = ds.cast(new_features)
 |      >>> ds.features
 |      {'label': ClassLabel(names=['bad', 'good']),
 |       'text': Value('large_string')}
 |      ```
 |
 |  cast_column(self, column: str, feature: Union[dict, list, tuple, datasets.features.features.Value, datasets.features.features.ClassLabel, datasets.features.translation.Translation, datasets.features.translation.TranslationVariableLanguages, datasets.features.features.LargeList, datasets.features.features.List, datasets.features.features.Array2D, datasets.features.features.Array3D, datasets.features.features.Array4D, datasets.features.features.Array5D, datasets.features.audio.Audio, datasets.features.image.Image, datasets.features.video.Video, datasets.features.pdf.Pdf], new_fingerprint: Optional[str] = None) -> 'Dataset'
 |      Cast column to feature for decoding.
 |
 |      Args:
 |          column (`str`):
 |              Column name.
 |          feature (`FeatureType`):
 |              Target feature.
 |          new_fingerprint (`str`, *optional*):
 |              The new fingerprint of the dataset after transform.
 |              If `None`, the new fingerprint is computed using a hash of the previous fingerprint, and the transform arguments.
 |
 |      Returns:
 |          [`Dataset`]
 |
 |      Example:
 |
 |      ```py
 |      >>> from datasets import load_dataset, ClassLabel
 |      >>> ds = load_dataset("cornell-movie-review-data/rotten_tomatoes", split="validation")
 |      >>> ds.features
 |      {'label': ClassLabel(names=['neg', 'pos']),
 |       'text': Value('string')}
 |      >>> ds = ds.cast_column('label', ClassLabel(names=['bad', 'good']))
 |      >>> ds.features
 |      {'label': ClassLabel(names=['bad', 'good']),
 |       'text': Value('string')}
 |      ```
 |
 |  class_encode_column(self, column: str, include_nulls: bool = False) -> 'Dataset'
 |      Casts the given column as [`~datasets.features.ClassLabel`] and updates the table.
 |
 |      Args:
 |          column (`str`):
 |              The name of the column to cast (list all the column names with [`~datasets.Dataset.column_names`])
 |          include_nulls (`bool`, defaults to `False`):
 |              Whether to include null values in the class labels. If `True`, the null values will be encoded as the `"None"` class label.
 |
 |              <Added version="1.14.2"/>
 |

In [ ]:
dataset["train"].to_pandas()

                                                    text  label
0      I rented I AM CURIOUS-YELLOW from my video sto...      0
1      "I Am Curious: Yellow" is a risible and preten...      0
2      If only to avoid making this type of film in t...      0
3      This film was probably inspired by Godard's Ma...      0
4      Oh, brother...after hearing about this ridicul...      0
...                                                  ...    ...
24995  A hit at the time but now better categorised a...      1
24996  I love this movie like no other. Another time ...      1
24997  This film and it's sequel Barry Mckenzie holds...      1
24998  'The Adventures Of Barry McKenzie' started lif...      1
24999  The story centers around Barry McKenzie who mu...      1

[25000 rows x 2 columns]

In [ ]:
dataset["train"].to_pandas()["text"]

0        I rented I AM CURIOUS-YELLOW from my video sto...
1        "I Am Curious: Yellow" is a risible and preten...
2        If only to avoid making this type of film in t...
3        This film was probably inspired by Godard's Ma...
4        Oh, brother...after hearing about this ridicul...
                               ...
24995    A hit at the time but now better categorised a...
24996    I love this movie like no other. Another time ...
24997    This film and it's sequel Barry Mckenzie holds...
24998    'The Adventures Of Barry McKenzie' started lif...
24999    The story centers around Barry McKenzie who mu...
Name: text, Length: 25000, dtype: object

In [ ]:
from transformers import pipeline

In [ ]:
pipe = pipeline("sentiment-analysis")

No model was supplied, defaulted to distilbert/distilbert-base-uncased-finetuned-sst-2-english and revision 714eb0f (https://huggingface.co/distilbert/distilbert-base-uncased-finetuned-sst-2-english).
Using a pipeline without specifying a model name and revision in production is not recommended.

config.json:   0%|          | 0.00/629 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/268M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

Device set to use cuda:0

In [ ]:
dataset_df = dataset["train"].to_pandas()
dataset_df

                                                    text  label
0      I rented I AM CURIOUS-YELLOW from my video sto...      0
1      "I Am Curious: Yellow" is a risible and preten...      0
2      If only to avoid making this type of film in t...      0
3      This film was probably inspired by Godard's Ma...      0
4      Oh, brother...after hearing about this ridicul...      0
...                                                  ...    ...
24995  A hit at the time but now better categorised a...      1
24996  I love this movie like no other. Another time ...      1
24997  This film and it's sequel Barry Mckenzie holds...      1
24998  'The Adventures Of Barry McKenzie' started lif...      1
24999  The story centers around Barry McKenzie who mu...      1

[25000 rows x 2 columns]

In [ ]:
pipe(dataset_df["text"].iloc[1])

[{'label': 'NEGATIVE', 'score': 0.9991909861564636}]

In [ ]:
def score(review_text):
    return pipe(review_text[:500])[0]["label"]

In [ ]:
dataset_df["model_prediction"] = dataset_df["text"].apply(score)

You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset

In [ ]:
dataset_df

,text,label,model_prediction
0,I rented I AM CURIOUS-YELLOW from my video sto...,0,NEGATIVE
1,"""I Am Curious: Yellow"" is a risible and preten...",0,NEGATIVE
2,If only to avoid making this type of film in t...,0,NEGATIVE
3,This film was probably inspired by Godard's Ma...,0,POSITIVE
4,"Oh, brother...after hearing about this ridicul...",0,NEGATIVE
...,...,...,...
24995,A hit at the time but now better categorised a...,1,NEGATIVE
24996,I love this movie like no other. Another time ...,1,POSITIVE
24997,This film and it's sequel Barry Mckenzie holds...,1,POSITIVE
24998,'The Adventures Of Barry McKenzie' started lif...,1,NEGATIVE
24999,The story centers around Barry McKenzie who mu...,1,POSITIVE

In [ ]:
from datasets import load_dataset

reviews = load_dataset("rotten_tomatoes")

README.md: 0.00B [00:00, ?B/s]

train.parquet:   0%|          | 0.00/699k [00:00<?, ?B/s]

validation.parquet:   0%|          | 0.00/90.0k [00:00<?, ?B/s]

test.parquet:   0%|          | 0.00/92.2k [00:00<?, ?B/s]

Generating train split:   0%|          | 0/8530 [00:00<?, ? examples/s]

Generating validation split:   0%|          | 0/1066 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/1066 [00:00<?, ? examples/s]

In [ ]:
pipe = pipeline(task="text-classification", model="ProsusAI/finbert")

config.json:   0%|          | 0.00/758 [00:00<?, ?B/s]

pytorch_model.bin:   0%|          | 0.00/438M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/252 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

model.safetensors:   0%|          | 0.00/438M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

Device set to use cuda:0

In [ ]:
pipe("The company reported a strong increase in quarterly revenue, exceeding market expectations.")

[{'label': 'positive', 'score': 0.9543071389198303}]

In [ ]:
pipe("Shares fell after the firm reported lower-than-expected earnings")

[{'label': 'negative', 'score': 0.9718543887138367}]

In [ ]:
sentences = ["Strong consumer demand drove record sales across all regions",
             "Supply chain disruptions severely affected production output."]

## Named Entity Recognition (My Example)

In [ ]:
sentence = "Apple announced record earnings in the United States on Monday"

In [ ]:
ner_tag_pipe = pipeline("ner")

No model was supplied, defaulted to dbmdz/bert-large-cased-finetuned-conll03-english and revision 4c53496 (https://huggingface.co/dbmdz/bert-large-cased-finetuned-conll03-english).
Using a pipeline without specifying a model name and revision in production is not recommended.

config.json:   0%|          | 0.00/998 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/1.33G [00:00<?, ?B/s]

Some weights of the model checkpoint at dbmdz/bert-large-cased-finetuned-conll03-english were not used when initializing BertForTokenClassification: ['bert.pooler.dense.bias', 'bert.pooler.dense.weight']
- This IS expected if you are initializing BertForTokenClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertForTokenClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).

tokenizer_config.json:   0%|          | 0.00/60.0 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

Device set to use cuda:0

In [ ]:
ner_tag_pipe(sentence)

[{'entity': 'I-ORG',
  'score': np.float32(0.99911004),
  'index': 1,
  'word': 'Apple',
  'start': 0,
  'end': 5},
 {'entity': 'I-LOC',
  'score': np.float32(0.99967754),
  'index': 7,
  'word': 'United',
  'start': 39,
  'end': 45},
 {'entity': 'I-LOC',
  'score': np.float32(0.9996001),
  'index': 8,
  'word': 'States',
  'start': 46,
  'end': 52}]

In [ ]:
ner_tag_pipe("Amazon expanded its logistics operations in Germany")

[{'entity': 'I-ORG',
  'score': np.float32(0.99928266),
  'index': 1,
  'word': 'Amazon',
  'start': 0,
  'end': 6},
 {'entity': 'I-LOC',
  'score': np.float32(0.999806),
  'index': 7,
  'word': 'Germany',
  'start': 44,
  'end': 51}]

----------------------------------------------------------------------
----------------------------------------------------------------------
----------------------------------------------------------------------

## Question Answering

In [ ]:
qa_bot = pipeline("question-answering")

No model was supplied, defaulted to distilbert/distilbert-base-cased-distilled-squad and revision 564e9b5 (https://huggingface.co/distilbert/distilbert-base-cased-distilled-squad).
Using a pipeline without specifying a model name and revision in production is not recommended.

config.json:   0%|          | 0.00/473 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/261M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/49.0 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

Device set to use cuda:0

In [ ]:
my_text = """
السماء لونها ازرق
"""

qa_bot(question="ما لون السماء", context=my_text)

{'score': 0.2881357427686453, 'start': 8, 'end': 18, 'answer': 'لونها ازرق'}

In [ ]:
text = """
The expansion began shortly after 2015 with rapid advances in deep learning and
large-scale data availability, driven by breakthroughs in neural network
architectures and GPU acceleration. The early phase of growth was marked by
significant investment from technology companies and research institutions,
alongside the deployment of AI systems in speech recognition, computer vision,
and recommendation engines. By the late 2010s, large-scale language models and
cloud-based AI services had emerged as central pillars of the industry.
The global AI ecosystem was divided into several major sectors: machine learning
 platforms, natural language processing, computer vision, autonomous systems,
 and AI-driven analytics. Competitive pressure accelerated innovation,
 particularly in foundation models and infrastructure, with companies racing
 to scale model size and efficiency. Regulatory scrutiny and ethical
 considerations began to shape deployment strategies, especially in
 healthcare, finance, and public services.
"""

In [ ]:
question = "When did the major expansion of the AI industry begin?"

In [ ]:
result = qa_bot(question=question, context=text)
result

{'score': 0.4866883456707001,
 'start': 21,
 'end': 39,
 'answer': 'shortly after 2015'}

In [ ]:
question = "What technological advances drove the early growth of the AI industry?"

In [ ]:
result = qa_bot(question=question, context=text)
result

{'score': 0.38779252767562866,
 'start': 122,
 'end': 188,
 'answer': 'breakthroughs in neural network\narchitectures and GPU acceleration'}

In [ ]:
text[122:188]

'breakthroughs in neural network\narchitectures and GPU acceleration'

In [ ]:
print(result["answer"])

breakthroughs in neural network
architectures and GPU acceleration

In [ ]:
my_text_knowledge = """
The sky is blue and pure. The earth has diversified geologicial details.
"""

In [ ]:
question = "What is the color of the sky"

qa_bot(question=question, context=my_text_knowledge)

{'score': 0.4470493197441101,
 'start': 12,
 'end': 25,
 'answer': 'blue and pure'}

### Electra Model For RAG Tasks

In [ ]:
# Use a pipeline as a high-level helper
from transformers import pipeline

pipe = pipeline("question-answering", model="ahotrod/electra_large_discriminator_squad2_512")

Device set to use cuda:0

In [ ]:
text = """
The expansion began shortly after 2015 with rapid advances in deep learning and
large-scale data availability, driven by breakthroughs in neural network
architectures and GPU acceleration. The early phase of growth was marked by
significant investment from technology companies and research institutions,
alongside the deployment of AI systems in speech recognition, computer vision,
and recommendation engines. By the late 2010s, large-scale language models and
cloud-based AI services had emerged as central pillars of the industry.
The global AI ecosystem was divided into several major sectors: machine learning
 platforms, natural language processing, computer vision, autonomous systems,
 and AI-driven analytics. Competitive pressure accelerated innovation,
 particularly in foundation models and infrastructure, with companies racing
 to scale model size and efficiency. Regulatory scrutiny and ethical
 considerations began to shape deployment strategies, especially in
 healthcare, finance, and public services.
"""

question = "What are the breakthroughs that made AI possible?"

print(qa_bot(question=question, context=text)["answer"])

neural network
architectures and GPU acceleration

----------------------------------------------------------------------
----------------------------------------------------------------------
----------------------------------------------------------------------

## Machine Translation

In [ ]:
translate = pipeline("translation_en_to_fr")

No model was supplied, defaulted to google-t5/t5-base and revision a9723ea (https://huggingface.co/google-t5/t5-base).
Using a pipeline without specifying a model name and revision in production is not recommended.

config.json: 0.00B [00:00, ?B/s]

model.safetensors:   0%|          | 0.00/892M [00:00<?, ?B/s]

generation_config.json:   0%|          | 0.00/147 [00:00<?, ?B/s]

spiece.model:   0%|          | 0.00/792k [00:00<?, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

Device set to use cuda:0

In [ ]:
translate("Hello")

[{'translation_text': 'Bonjour'}]

In [ ]:
translate("Thanks")

[{'translation_text': 'Merci'}]

In [ ]:
translate("Artificial intelligence is transforming many industries around the world")

[{'translation_text': "L'intelligence artificielle transforme de nombreuses industries dans le monde"}]

----------------------------------------------------------------------
----------------------------------------------------------------------
----------------------------------------------------------------------